### ISSUE TITLE
What's the password?

### ISSUE THREAD

**Issue by eddca** [StackStorm/st2-ansible-vagrant#3]
Hello,

When I type vagrant up, vangrat is prompting me for password.
http://i.imgur.com/aq7XVq4.png

Following passwords does not work:

- demo
- root
- admin
- vagrant

What's the password guys?

**Comment by LindsayHill** [comment]
It looks like your screenshot is a bit cut off. Can you provide a few more lines before that? I suspect that it's actually `sudo` asking for *your* password on *your* host machine, so it can add local hosts entries using the vagrant-hostmanager plugin.

**Comment by arm4b** [comment]
Closing due to no reply from the reporter for a long time
