### ISSUE TITLE
Error during Ansible installation: missing gssapi/gssapi.h

### ISSUE THREAD

**Issue by vatima2016** [StackStorm/st2-ansible-vagrant#4]
Installing libkrb5-dev on the master node as decsribed here https://github.com/rvagg/node-libssh/issues/48 and rerunning failed Ansible pack installation resolved this particular issue.
But the rest of the demo setup stayed broken, so I've workarounded it by:
1) inserting additional provisioning shell script vm_config.vm.provision :shell, path: "fix_kerberos.sh" before the stackstorm installation in the Vagrantfile having the following content:
set -e
sudo apt-get install libkrb5-dev --assume-yes
2) destroying everything
3) and running vagrant up again

**Comment by arm4b** [comment]
Indeed, thanks for the report!

Considering a known fix, would you like to submit a PR which will install Ansible [OS package requirements](https://github.com/stackstorm-exchange/stackstorm-ansible#requirements)?

It could fit existing [`ansible.sh`](https://github.com/StackStorm/st2-ansible-vagrant/blob/master/ansible.sh#L2).
